const projects = [
  {short:"Account takeover",eyebrow:"Fraud case study",title:"Account takeover review",description:"The account looked ordinary until a new device appeared, the password changed, and contact details were updated within minutes. I treated each event as one part of a timeline instead of assuming that any single change proved fraud.",context:"The exercise began with a fictional customer reporting that access no longer worked. The activity log included a successful login from a new device followed by several sensitive profile changes.",question:"Do the access and profile changes support a credible account-takeover concern?",steps:["Built an activity timeline","Isolated login and profile-change indicators","Prepared an evidence-based escalation rationale"],outcome:"Escalate for additional identity verification and preserve the activity timeline for review.",takeaway:"The strongest signal was not one unusual event. It was the speed and order of several related events.",tags:["Account takeover","Evidence review","Escalation"]},
  {short:"Transaction alert",eyebrow:"Transaction case study",title:"Pattern and alert review",description:"A transaction alert showed activity that was individually possible but collectively unusual. I compared the amount, timing, frequency, and location with the customer’s established pattern before deciding what deserved escalation.",context:"The fictional account normally showed modest domestic spending. The alert involved several larger transactions in a short period and a change from the account’s usual behavior.",question:"Does the transaction behavior materially differ from the fictional customer’s expected activity?",steps:["Established expected behavior","Compared amount, frequency, and timing","Recorded a concise alert disposition"],outcome:"Escalate the activity because multiple deviations appeared together rather than as a single isolated event.",takeaway:"A useful review explains the difference between unusual activity and activity that is unusual for this particular account.",tags:["Transaction patterns","Anomaly review","Risk decision"]},
  {short:"E-commerce order",eyebrow:"E-commerce case study",title:"High-risk order review",description:"A newly created account placed a high-value order after several declined payment attempts. I reviewed the full order story, including account age, address differences, payment behavior, and order value, before choosing a proportionate response.",context:"The fictional order used different billing and shipping addresses and followed multiple unsuccessful card attempts. None of those details alone was enough to make the decision.",question:"Should the order be approved, declined, or sent for additional verification?",steps:["Compared billing and shipping details","Reviewed payment-attempt pattern","Applied a structured approve-or-escalate decision"],outcome:"Hold for verification because several moderate indicators combined into a higher-risk pattern.",takeaway:"Good order review protects the business without automatically treating every address mismatch as fraud.",tags:["E-commerce fraud","Order review","Payment risk"]},
  {short:"Identity review",eyebrow:"Identity case study",title:"Identity discrepancy review",description:"The submitted identity information almost matched the account profile, but several fields differed. I separated harmless formatting variations from inconsistencies that affected confidence in the identity.",context:"The fictional file included an identification record, an account application, and supporting address information with a mixture of exact matches and discrepancies.",question:"Are the differences explainable, or do they require a verification hold?",steps:["Cross-checked identity fields","Separated minor variations from material gaps","Documented the verification decision"],outcome:"Request additional verification for unresolved differences in core identity information.",takeaway:"The goal is not to flag every difference. It is to recognize which differences actually matter to the decision.",tags:["Identity verification","Document review","Data accuracy"]},
  {short:"Chargeback review",eyebrow:"Disputes case study",title:"Chargeback evidence review",description:"A card transaction was disputed after delivery. I organized the timeline and compared the transaction, account activity, delivery record, and dispute reason to see what the evidence established and what it did not.",context:"The fictional evidence package contained a transaction record and delivery confirmation, but important links between the customer, order, and delivery were incomplete.",question:"Is the available evidence complete and internally consistent enough to support a response?",steps:["Organized transaction evidence","Checked dates and account activity","Identified missing support"],outcome:"Refer for follow-up because the evidence package does not fully resolve the disputed activity.",takeaway:"A responsible decision acknowledges missing evidence instead of forcing certainty where the record is incomplete.",tags:["Chargebacks","Evidence package","Disputes"]},
  {short:"Business review",eyebrow:"Business review case study",title:"Business customer review",description:"A business application named several owners but left part of the control structure unclear. I mapped the information that was available, identified what was missing, and avoided filling gaps with assumptions.",context:"The fictional file included registration details, ownership percentages, and identification information for some, but not all, people connected to the company.",question:"Is the fictional business record complete enough to support a customer-risk review?",steps:["Mapped ownership information","Reviewed beneficial-owner details","Documented risk factors and gaps"],outcome:"Request missing ownership information before completing the review.",takeaway:"Completeness matters. A tidy-looking file can still be unsuitable for a decision when ownership information is unresolved.",tags:["KYC / CDD","Beneficial ownership","Record review"]}
];
let activeIndex=0;
const tabs=document.querySelector('.project-tabs');
projects.forEach((project,index)=>{const button=document.createElement('button');button.type='button';button.setAttribute('role','tab');button.innerHTML=`<span>${String(index+1).padStart(2,'0')}</span>${project.short}`;button.addEventListener('click',()=>render(index));tabs.appendChild(button)});
function render(index){activeIndex=index;const p=projects[index];[...tabs.children].forEach((b,i)=>{b.classList.toggle('active',i===index);b.setAttribute('aria-selected',String(i===index))});document.querySelector('#project-number').textContent=`${String(index+1).padStart(2,'0')} / ${String(projects.length).padStart(2,'0')}`;document.querySelector('#project-eyebrow').textContent=p.eyebrow;['title','description','context','question','outcome'].forEach(k=>document.querySelector(`#project-${k}`).textContent=p[k]);document.querySelector('#project-takeaway').textContent=`“${p.takeaway}”`;document.querySelector('#project-steps').innerHTML=p.steps.map((s,i)=>`<div><span>0${i+1}</span><p>${s}</p></div>`).join('');document.querySelector('#project-tags').innerHTML=p.tags.map(t=>`<span>${t}</span>`).join('')}
document.querySelector('#previous').addEventListener('click',()=>render((activeIndex-1+projects.length)%projects.length));
document.querySelector('#next').addEventListener('click',()=>render((activeIndex+1)%projects.length));
render(0);
